# Generated by Django 4.2.7 on 2023-11-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcureIt_0_0_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceivedNote',
            fields=[
                ('grnid', models.AutoField(primary_key=True, serialize=False)),
                ('grnnumber', models.IntegerField(unique=True)),
                ('grndate', models.DateTimeField(auto_now_add=True)),
                ('deliverynotenumber', models.CharField(max_length=25)),
                ('supplierinvoicenumber', models.CharField(max_length=25)),
                ('receivedby', models.CharField(max_length=256)),
                ('orderedqty', models.IntegerField()),
                ('receivedqty', models.IntegerField()),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('ordernumber', models.IntegerField()),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('totalamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='bookcontributor',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'Author'), ('CO_AUTHOR', 'Co-Author'), ('EDITOR', 'Editor')], max_length=20, verbose_name='The role this contributor had in the book.'),
        ),
    ]
