# Generated by Django 4.2.7 on 2023-11-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProcureIt_0_0_1', '0002_goodsreceivednote_purchaseorder_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchaseorder',
            table='p_order',
        ),
    ]
