# Generated by Django 4.2.7 on 2023-11-09 06:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProcureIt_0_0_1', '0003_alter_purchaseorder_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendorid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=128)),
                ('contact_name', models.CharField(max_length=128)),
                ('contact_email', models.EmailField(blank=True, max_length=128, null=True)),
                ('contact_phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'vendors',
            },
        ),
        migrations.AlterModelTable(
            name='goodsreceivednote',
            table='gr_notes',
        ),
        migrations.AlterModelTable(
            name='purchaseorder',
            table='purchaseorders',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendorid',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ProcureIt_0_0_1.vendor'),
            preserve_default=False,
        ),
    ]
