# Generated by Django 4.2.7 on 2023-11-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcureIt_0_0_1', '0004_vendor_alter_goodsreceivednote_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='ordernumber',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendorid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
