# Generated by Django 4.2.7 on 2023-11-09 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProcureIt_0_0_1', '0005_alter_purchaseorder_ordernumber_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendor',
            new_name='Vendors',
        ),
        migrations.RenameModel(
            old_name='GoodsReceivedNote',
            new_name='GoodsReceivedNotes',
        ),
        migrations.RenameModel(
            old_name='PurchaseOrder',
            new_name='PurchaseOrders',
        ),
        migrations.CreateModel(
            name='PurchaseOrderItems',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProcureIt_0_0_1.purchaseorders')),
            ],
            options={
                'db_table': 'po_items',
            },
        ),
        migrations.CreateModel(
            name='GRNItems',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=128)),
                ('orderedqty', models.IntegerField()),
                ('receivedqty', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProcureIt_0_0_1.goodsreceivednotes')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProcureIt_0_0_1.purchaseorders')),
            ],
            options={
                'db_table': 'grnitems',
            },
        ),
    ]
