# Generated by Django 4.2.7 on 2023-11-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProcureIt_0_0_1', '0007_remove_grnitems_po_goodsreceivednotes_po'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsreceivednotes',
            old_name='po',
            new_name='poid',
        ),
        migrations.RenameField(
            model_name='grnitems',
            old_name='item_id',
            new_name='grnitem_id',
        ),
        migrations.RenameField(
            model_name='purchaseorderitems',
            old_name='item_id',
            new_name='po_item_id',
        ),
    ]
