# Generated by Django 4.2.7 on 2023-11-09 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProcureIt_0_0_1', '0008_rename_po_goodsreceivednotes_poid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorders',
            name='vendorid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ProcureIt_0_0_1.vendors'),
        ),
    ]
