# Generated by Django 4.2.7 on 2023-11-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProcureIt_0_0_1', '0009_alter_purchaseorders_vendorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grnitems',
            old_name='grnitem_id',
            new_name='grnitemid',
        ),
    ]
