# Generated by Django 4.2.7 on 2023-11-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcureIt_0_0_1', '0010_rename_grnitem_id_grnitems_grnitemid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcontributor',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookcontributor',
            name='contributor',
        ),
        migrations.AlterField(
            model_name='goodsreceivednotes',
            name='orderedqty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goodsreceivednotes',
            name='receivedqty',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookContributor',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
